with-expecter: true
dir: "{{.InterfaceDir}}"
outpkg: "{{.PackageName}}mocks"
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  hello-go/internal:
    interfaces:
      CourseRepository:
        config:
          dir: "internal/platform/storage/storagemocks"
          outpkg: "storagemocks"
          filename: "course_repository.go"
